# Generated by Django 5.1.6 on 2025-03-05 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Organization')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Is Teacher')),
                ('is_student', models.BooleanField(default=False, verbose_name='Is Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
