# Generated by Django 5.1.6 on 2025-03-05 21:07

import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='Icon Class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'External Link'), ('image', 'Image'), ('audio', 'Audio'), ('interactive', 'Interactive Content')], max_length=20, verbose_name='Resource Type')),
                ('audience', models.CharField(choices=[('all', 'All Ages'), ('children', 'Children'), ('teenagers', 'Teenagers'), ('adults', 'Adults'), ('teachers', 'Teachers'), ('parents', 'Parents')], default='all', max_length=20, verbose_name='Target Audience')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/', verbose_name='Thumbnail')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='File')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', verbose_name='Video URL')),
                ('external_url', models.URLField(blank=True, verbose_name='External URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('level', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('higher', 'Higher Education')], max_length=20, verbose_name='Education Level')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('file', models.FileField(upload_to='teaching_materials/', verbose_name='File')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='teaching_materials/thumbnails/', verbose_name='Thumbnail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Teaching Material',
                'verbose_name_plural': 'Teaching Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
